---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[stackstorm::default]
    attributes:
  - name: rabbitmq
    run_list:
      - recipe[stackstorm::rabbitmq]
    attributes:
